name: e2e


on:
  pull_request:
    types: [opened, closed, merged,synchronize]
jobs:
  build-and-wp-deploy:
    runs-on: ubuntu-latest
    if: github.event.action == 'opened' || github.event.action == 'synchronize'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build CSS and JS first
        run: yarn && yarn build
      - name: Zip Plugin
        id: pluginmachine
        uses: imaginarymachines/builder-action@main
        with:
          PLUGIN_MACHINE_TOKEN:  ${{ secrets.PLUGIN_MACHINE_TOKEN }}
          PLUGIN_DIR: ${{ github.workspace }}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          COMMENT_PR: true
      - name: ZIP URL
        run: echo ${{steps.pluginmachine.outputs.upload}}
      - uses: instawp/wordpress-testing-automation@main
        id: create-wp
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          INSTAWP_TOKEN: ${{secrets.INSTAWP_TOKEN}}
          INSTAWP_DOMAIN: ${{secrets.INSTAWP_DOMAIN}}
          INSTAWP_TEMPLATE_SLUG: vendor
          REPO_ID: 4
          INSTAWP_ACTION: create-site-template
          ARTIFACT_URL: ${{steps.pluginmachine.outputs.upload}}
      - name: InstaWP URL
        run: echo URL ${{ steps.create-wp.outputs.instawp_url }}
        shell: bash

  destroy-wp-after-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: instawp/wordpress-testing-automation@main
        if: github.event.action == 'closed' || github.event.action == 'merged'
        id: detroy-wp
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          INSTAWP_TOKEN: ${{secrets.INSTAWP_TOKEN}}
          INSTAWP_DOMAIN: ${{secrets.INSTAWP_DOMAIN}}
          INSTAWP_TEMPLATE_SLUG: vendor
          REPO_ID: 4
          INSTAWP_ACTION: destroy-site
